# Generated by Django 3.2.6 on 2022-04-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser_info',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='advertiser_info',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='advertiser_info',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
