# Generated by Django 3.2.6 on 2022-04-29 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisers', '0002_auto_20220428_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='ad_info',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('media', models.CharField(max_length=100)),
                ('advertiser', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='advertisers.advertiser_info')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='result_data_set',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('media', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('cost', models.PositiveIntegerField(default=0)),
                ('impression', models.IntegerField(default=0)),
                ('click', models.PositiveIntegerField(default=0)),
                ('conversion', models.IntegerField(default=0)),
                ('cv', models.IntegerField(default=0)),
                ('advertiser', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='advertisers.advertiser_info')),
                ('uid', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='ads.ad_info')),
            ],
        ),
        migrations.AddIndex(
            model_name='result_data_set',
            index=models.Index(fields=['advertiser', 'date'], name='ads_result__adverti_8fb98d_idx'),
        ),
        migrations.AddIndex(
            model_name='result_data_set',
            index=models.Index(fields=['media'], name='ads_result__media_e39b19_idx'),
        ),
    ]
