# Generated by Django 3.2.6 on 2022-04-28 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ad_info',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('media', models.CharField(max_length=100)),
                ('advertiser_id', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='advertisers.advertiser_info')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='result_data_set',
            fields=[
                ('uid', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ads.ad_info')),
                ('media', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('cost', models.IntegerField()),
                ('impression', models.IntegerField()),
                ('click', models.IntegerField()),
                ('conversion', models.IntegerField()),
                ('cv', models.IntegerField()),
                ('advertiser_id', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='advertisers.advertiser_info')),
            ],
        ),
    ]
