# Generated by Django 3.2.6 on 2022-04-28 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad_info',
            old_name='advertiser_id',
            new_name='advertiser',
        ),
        migrations.RenameField(
            model_name='result_data_set',
            old_name='advertiser_id',
            new_name='advertiser',
        ),
    ]
